MyChess/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import activate

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),  # email varification
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    #apps
    path('accounts/',include('accounts.api.urls',namespace='accounts')),
    path('subscription/',include('usubscription.api.urls',namespace='usubscription')),
    path('category/',include('category.api.urls',namespace='category')),
    path('articles/',include('articles.api.urls',namespace='articles')),
    path('game/',include('game.api.urls',namespace='game')),
    path('tournament/',include('tournament.api.urls',namespace='tournament')),
    path('lessons/',include('lessons.api.urls',namespace='lessons')),
    path('achievement/',include('achievement.api.urls',namespace='achievement')),
    path('puzzles/',include('puzzles.api.urls',namespace='puzzles')),
    #admin_panel
    path('admin_panel/',include('_admin_panel.aaccounts.urls',namespace="ap_accounts")),
    path('admin_panel/articles/',include('_admin_panel.aarticles.urls',namespace='ap_articles')),
    path('admin_panel/videos/',include('_admin_panel.avideos.urls',namespace='ap_videos')),
    path('admin_panel/tournament/',include('_admin_panel.atournament.urls',namespace='ap_tournament')),
    path('admin_panel/usermgmt/',include('_admin_panel.ausermgmt.urls',namespace='ap_usermgmt')),
    path('admin_panel/settings/',include('_admin_panel.asettings.urls',namespace='ap_settings')),
    path('admin_panel/notification/',include('_admin_panel.anotification.urls',namespace='ap_notification')),
    path('admin_panel/lessons/',include('_admin_panel.alessons.urls',namespace='ap_lessons')),
    path('admin_panel/gametime/',include('_admin_panel.agametime.urls',namespace='ap_gametime')),
    path('admin_panel/subscription/',include('_admin_panel.asubscription.urls',namespace='ap_subscription')),
    path('admin_panel/leaderboard/',include('_admin_panel.aleaderboard.urls',namespace='ap_leaderboard')),
    path('admin_panel/achievement/',include('_admin_panel.aachievement.urls',namespace='ap_achievement')),
    path('admin_panel/payment/',include('_admin_panel.apayment.urls',namespace='ap_payment')),
    path('admin_panel/puzzles/',include('_admin_panel.apuzzles.urls',namespace='ap_puzzles')),
]
# urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_admin_panel/asubscription/urls.py
from django.urls import path
from .views import *
app_name='ap_subscription'

urlpatterns = [
    path('list',SubscriptionListView.as_view(),name='aps_list'),
    path('add',AddSubscriptionView.as_view(),name='aps_add'),
    path('edit/<int:pk>',EditSubscriptionView.as_view(),name='aps_edit'),
    path('view/<int:pk>',ViewSubscriptionView.as_view(),name='aps_view'),
    path('import',ImportSubscriptionView.as_view(),name='aps_import'),
]

accounts/api/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns=[
    path('countrycode_list',CountryCodeListView.as_view(),name='countrycode_list'),
    path('register',RegisterUserView.as_view(),name='register'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('forgot_password',ForgotPasswordView.as_view(),name='forgot_password'),
    path('otp_send',OTPSendView.as_view(),name='otp_send'),
    path('otp_verify',OTPVerifyAPIView.as_view(),name='otp_verify'),
    path('pass_reset_email',PasswordResetEmailView.as_view(),name='pass_reset_email'),
    path('verify_email',VerifyEmailView.as_view(),name='verify_email'),
    path('create_profile',CreateProfileView.as_view(),name="create_profile"),
    path('update_skill_level',UpdateSkillLevelView.as_view(),name='update_skill_level'),
    path('get_skill_level_list',GetSkillLevelListView.as_view(),name='get_skill_level_list_view'),

    path('block_unblock_user/<int:pk>',BlockUnblockUser.as_view(),name='block_unblock_user'),

    # path('create_notification_group',CreateNotificationGroup.as_view(),name='create_notification_group'),
    path('delete_notification_group/<int:pk>',DeleteNotificationGroup.as_view(),name='delete_notification_group'),
    path('view_notification_group/<int:pk>',ViewNotificationGroup.as_view(),name='view_notification_group'),

    path('many_user_list',ManyUserListView.as_view(),name='many_user_list'),
    path('get_random_online_user',GetRandomOnlineUserView.as_view(),name='get_random_online_user'),


    path('leaderboard/<int:pk>',LeaderBoardView.as_view(),name='get_leaderboard'),
    path('scoreboard',ScoreboardView.as_view(),name='get_scoreboard'),

    
    path('send_notification',SendNotificationView.as_view(),name='send_notification'),

]

_admin_panel/asubscription/models.py
from django.db import models

# Create your models here.

_admin_panel/asubscription/forms.py
from django import forms
from django.contrib.auth.models import User

from usubscription.models import *
from accounts.models import *


class AddSubscriptionForm(forms.Form):
    def clean(self):
        name=self.data['name']
        # duration_m=self.data['duration_m']
        # duration_y=self.data['duration_y']
        price_m=self.data['price_m']
        price_y=self.data['price_y']
        benefits=self.data['benefits']
        if not name or name=="":
            raise forms.ValidationError('Please provide name')
        # if not duration_m or duration_m=="":
        #     raise forms.ValidationError('Please provide (monthly) duration')
        # if not duration_y or duration_y=="":
        #     raise forms.ValidationError('Please provide (yearly) duration')
        if not price_m or price_m=="":
            raise forms.ValidationError('Please provide (monthly) price')
        if not price_y or price_y=="":
            raise forms.ValidationError('Please provide (yearly) price')
        if not benefits or benefits=="":
            raise forms.ValidationError('Please provide benefits')

        p1 = price_m.split('.')
        if len(p1)>2:
            raise forms.ValidationError('Price(monthly) is invalid')
        if not p1[0].isdigit():
            raise forms.ValidationError('Price(monthly) is invalid')
        if len(p1)==2 and (not p1[1].isdigit()):
            raise forms.ValidationError('Price(monthly) is invalid')

        p2 = price_y.split('.')
        if len(p2)>2:
            raise forms.ValidationError('Price(yearly) is invalid')
        if not p2[0].isdigit():
            raise forms.ValidationError('Price(yearly) is invalid')
        if len(p2)==2 and (not p2[1].isdigit()):
            raise forms.ValidationError('Price(yearly) is invalid')

        # if duration_m not in ['1','2','3','4','5','6','7','8','9','10','11']:
        #     raise forms.ValidationError('Duration(monthly) is not valid')
        # if duration_y not in ['1','2','3','4','5']:
        #     raise forms.ValidationError('Duration(yearly) is not valid')
        
        

_admin_panel/asubscription/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy,reverse
from django.contrib import messages
import openpyxl
from usubscription.models import *
from accounts.models import *
from .forms import *
# Create your views here.

class SubscriptionListView(TemplateView):
    def get(self,request,*args, **kwargs):
        subs = SubscriptionPlan.objects.filter(is_deleted=False)
        return render(request,'asubscription/subscriptions.html',{'subs':subs})

class AddSubscriptionView(TemplateView):
    def get(self,request,*args, **kwargs):
        return render(request,'asubscription/add-subscription.html')
    def post(self,request,*args, **kwargs):
        context={}
        context['name']=request.POST['name']
        # context['duration_m']=request.POST['duration_m']
        # context['duration_y']=request.POST['duration_y']
        context['price_m']=request.POST['price_m']
        context['price_y']=request.POST['price_y']
        context['benefits']=request.POST['benefits']
        form=AddSubscriptionForm(data=request.POST or None,)
        if form.is_valid():
            # period_m=str(int(context['duration_m'])-1)
            # period_y=str(int(context['duration_y'])-1)
            sp = SubscriptionPlan(
                plan_name=context['name'],
                # period_m=context['duration_m'],
                price_m=context['price_m'],
                # period_y=context['duration_y'],
                price_y=context['price_y'],
                description=context['benefits'],
            )
            sp.save()
            message='Plan saved successfully'
            messages.add_message(request, messages.INFO, message)
            return render(request,'asubscription/add-subscription.html')
        return render(request,'asubscription/add-subscription.html',context={'con':context,'form':form})

class EditSubscriptionView(TemplateView):
    def get(self,request,*args, **kwargs):
        id = self.kwargs['pk']
        con = SubscriptionPlan.objects.filter(id=id).first()
        # pb = PlanBenifits.objects.filter(plan=s).first()
        return render(request,'asubscription/subscription-edit.html',{'con':con})
    def post(self,request,*args, **kwargs):
        context={}
        context['id'] = self.kwargs['pk']
        context['plan_name']=request.POST['name']
        # context['period_m']=request.POST['duration_m']
        # context['period_y']=request.POST['duration_y']
        context['price_m']=request.POST['price_m']
        context['price_y']=request.POST['price_y']
        context['description']=request.POST['benefits']
        form=AddSubscriptionForm(data=request.POST or None,)
        if form.is_valid():
            # period_m=str(int(context['period_m'])-1)
            # period_y=str(int(context['duration_y'])-1)
            subp = SubscriptionPlan.objects.filter(id=context['id']).first()
            if subp:
                subp.plan_name=context['plan_name']
                # subp.period_m=context['period_m']
                subp.price_m=context['price_m']
                # subp.period_y=context['period_y']
                subp.price_y=context['price_y']
                subp.description=context['description']
                subp.save()
                message='Plan saved successfully'
                messages.add_message(request, messages.INFO, message)
                return HttpResponseRedirect('/admin_panel/subscription/view/'+str(context['id']))
            else:
                message='Invalid plan id'
            
        messages.add_message(request, messages.INFO, message)
        return render(request,'asubscription/subscription-edit.html',context={'con':context,'form':form})

class ViewSubscriptionView(TemplateView):
    def get(self,request,*args, **kwargs):
        id = self.kwargs['pk']
        s = SubscriptionPlan.objects.filter(id=id).first()
        # pb = PlanBenifits.objects.filter(plan=s).first()
        return render(request,'asubscription/view-subscription.html',{'s':s})

class ImportSubscriptionView(TemplateView):
    def post(self,request,*args,**kwargs):
        message=''
        excel_file = request.FILES["excel_file"]
        wb = openpyxl.load_workbook(excel_file)
        worksheet = wb["Sheet1"]
        excel_data = list()
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)
        status = validate_excel(excel_data)
        if status!="1":
            messages.add_message(request, messages.INFO, status)
            return HttpResponseRedirect('/admin_panel/subscription/list')     
        counter=0
        for row_data in excel_data:
            counter+=1
            if counter!=1:
                ach = SubscriptionPlan(
                    plan_name=row_data[0],
                    # period_m=row_data[1],
                    # period_y=row_data[2],
                    price_m=row_data[3],
                    price_y=row_data[4],
                    description=row_data[5],
                )
                ach.save()
                message='Data saved successfully'
        messages.add_message(request, messages.INFO, message)
        return HttpResponseRedirect('/admin_panel/subscription/list')  

def validate_excel(excel_data):
    counter=0
    less_id_list=[]
    if len(excel_data[0])<3:
        return 'Please use proper excel file format'
    for row_data in excel_data:
        counter += 1
        name=row_data[0]
        price_m=row_data[1]
        price_y=row_data[2]
        benefits=row_data[3]
        # duration_m=row_data[1]
        # duration_y=row_data[2]
        # price_m=row_data[3]
        # price_y=row_data[4]
        # benefits=row_data[5]
        # if counter==1:
        #     if (name!='Name' or duration_m!='Duration(Monthly)' 
        #         or duration_y!='Duration(Yearly)' or price_m!='Price(Monthly)' 
        #         or price_y!='Price(Yearly)' or benefits!='Benefits'):
        #         return 'Please use proper excel file format'
        if counter==1:
            if (name!='Name' or price_m!='Price(Monthly)' 
                or price_y!='Price(Yearly)' or benefits!='Benefits'):
                return 'Please use proper excel file format'
        else:
            if not name or name=="":
                return 'Please provide name at row '+str(counter)
            # if not duration_m or duration_m=="":
            #     return 'Please provide duration(monthly) '+str(counter)
            # if not duration_y or duration_y=="":
            #     return 'Please provide duration(yearly) '+str(counter)
            if not price_m or price_m=="":
                return 'Please provide price(monthly) at row '+str(counter)
            if not price_y or price_y=="":
                return 'Please provide price(yearly) '+str(counter)
            if not benefits or benefits=="":
                return 'Please provide benefits '+str(benefits)

            if len(name)>40:
                return "Name length is exceeding at row "+str(counter)
            # if len(duration_m)>10:
            #     return "Duration(monthly) length is exceeding at row "+str(counter)
            # if len(duration_m)>10:
            #     return "Duration(yearly) is exceeding at row "+str(counter)
            if len(price_m)>10:
                return "Price(monthly) length is exceeding at row "+str(counter)
            if len(price_y)>10:
                return "Price(yearly) is exceeding at row "+str(counter)
            if len(benefits)>900:
                return "Benefits length is exceeding at row "+str(counter)
            
            p1 = price_m.split('.')
            if len(p1)>2:
                return 'Price(monthly) is invalid at row '+str(counter)
            if not p1[0].isdigit():
                return 'Price(monthly) is invalid at row '+str(counter)
            if len(p1)==2 and (not p1[1].isdigit()):
                return 'Price(monthly) is invalid at row '+str(counter)

            p2 = price_y.split('.')
            if len(p2)>2:
                return 'Price(yearly) is invalid at row '+str(counter)
            if not p2[0].isdigit():
                return 'Price(yearly) is invalid at row '+str(counter)
            if len(p2)==2 and (not p2[1].isdigit()):
                return 'Price(yearly) is invalid at row '+str(counter)

            # if duration_m not in ['1','2','3','4','5','6','7','8','9','10','11']:
            #     return 'Duration(monthly) is not valid at row '+str(counter)
            # if duration_y not in ['1','2','3','4','5']:
            #      return 'Duration(yearly) is not valid at row '+str(counter)

    if counter in (0,1):
        return "Excel file is empty"
    return "1"

_admin_panel/asubscription/templates/asubscription/subscriptions.html
{% load staticfiles %}
{% include 'base/header-link.html' %}
{% include 'base/header.html' %}
<div class="layout-main">
    {% include 'base/sidebar.html' %}

    <div class="subscriptionsPage ExplorerListPage">
        <div class="layout-content">
            <div class="layout-content-body">
                    <div class="row margin-bottom-15">
                        <div class="col-md-12">
                            <div class="title-bar">
                                <h1 class="title-bar-title">
                                    <span class="d-ib">Subscription Management</span>
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row margin-bottom-15">
                        <div class="col-sm-8"></div>
                        <div class="col-sm-5">
                            <label style="color:blue;">After importing the file please click the submit button</label>
                        </div>
                    </div>
                    <div class="row margin-bottom-15">
                        
                        <div class="col-sm-3">
                            <!-- <div class="form-group">
                            <label for="" class="control-label">Duration</label>
                            <select class="form-control" name="status">
                                <option value="1">Monthly</option>
                                <option value="0">Yearly</option>
                            </select>
                            </div> -->
                        </div>
                        
                        <div class="col-sm-9">
                            <form action="{% url 'ap_subscription:aps_import' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="add_member category-select">
                                    
                                    <input type="file" accept=".xls,.xlsx" name="excel_file" id="import" onchange="showImportSubmit(); return false;" class="hidden">
                                    <a class="btn btn-danger btn-sm btn-labeled" href="{% url 'ap_subscription:aps_add' %}">
                                        <span class="btn-label">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                        </span>
                                        ADD
                                    </a>
                                    <label class="btn btn-danger btn-sm btn-labeled" for="import">
                                        <span class="btn-label">
                                        <i class="fa fa-file-excel-o" aria-hidden="true"></i>
                                        </span>
                                        Import
                                    </label>
                                    <button id="importSubmit" class="btn btn-danger btn-sm btn-labeled" type="submit" style="display: none;">
                                        <span class="btn-label">
                                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                                        </span>
                                        Submit
                                    </button>
                                    {% if messages %}
                                        {% for message in messages %}
                                            <p style="color:green;">{{message}}</p>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </form> 
                        </div>  
                    </div> 
                <div class="row gutter-xs">
                    <div class="col-xs-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="6%">S.No ID</th>
                                            <th>S Name</th>
                                            <!-- <th>Duration(Monthly)</th> -->
                                            <th>Price(Monthly)</th>
                                            <!-- <th>Duration(Yearly)</th> -->
                                            <th>Price(Yearly)</th>
                                            <th width="20%">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for s in subs %}
                                        <tr>
                                            <td>{{s.id}}</td>
                                            <td>{{s.plan_name}}</td>
                                            <!-- <td>{{s.period_m}}</td> -->
                                            <td>{{s.price_m}}</td>
                                            <!-- <td>{{s.period_y}}</td> -->
                                            <td>{{s.price_y}}</td>
                                            <td>
                                            <button class="btn btn-danger btn-sm btn-labeled" type="button" data-toggle="modal" data-target="#deleteUser" id="{{s.id}}" onclick="delete_ach(this.id)">
                                                <span class="btn-label">
                                                <span class="icon fa fa-trash icon-fw icon-lg f-16"></span>
                                                </span>
                                                Delete
                                            </button>
                                            <a class="btn btn-primary btn-sm btn-labeled" href="{% url 'ap_subscription:aps_view' s.id %}">
                                                <span class="btn-label">
                                                <span class="icon fa fa-eye icon-fw icon-lg f-16"></span>
                                                </span>
                                                View
                                            </a>
                                            {% if s.is_blocked %}
                                                <button class="btn btn-default btn-sm btn-labeled" type="button" id="{{s.id}}">
                                                    <span class="btn-label">
                                                        <label class="mr-2 switch product-switch">
                                                            <input id="{{s.id}}" type="checkbox" onchange="block_unblock(this.id)">
                                                            <span class="slider round product-slide"></span>
                                                        </label>
                                                    </span>
                                                    <label id="{{s.id}}" for="">Unblock</label>
                                                </button>
                                            {% else %}
                                                <button class="btn btn-default btn-sm btn-labeled" type="button" id="{{s.id}}">
                                                    <span class="btn-label">
                                                        <label class="mr-2 switch product-switch">
                                                            <input id="{{s.id}}" type="checkbox" checked="" onchange="block_unblock(this.id)">
                                                            <span class="slider round product-slide"></span>
                                                        </label>
                                                    </span>
                                                    <label id="{{s.id}}" for="">Block</label>
                                                </button>
                                            {% endif %}
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}
    {% include 'base/footer-link.html' %}
    
    <div id="deleteUser" tabindex="-1" role="dialog" class="modal fade">
     <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-body">
            <div class="text-center">
              <h4>Are you sure you want to Delete this Lesson categories?</h4>
              <div class="m-t-lg">
                <button class="btn btn-red" id="deleteach_id" data-dismiss="modal" type="button" achid="" data-toggle="modal" onclick="conf_delete()">Continue</button>
                <button class="btn btn-default" data-dismiss="modal" type="button">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div>      
    </div>
   
    <!-- Modal -->
<div class="modal fade" id="exampleModalLong">
    <div class="modal-dialog modal-sm" data-dismiss="modal">
        <div class="modal-content">
            <div class="modal-body">
            <div class="successful-icon text-center">
            <i class="fa fa-check-square-o" aria-hidden="true" style="font-size: 22px;color: #17b517;"></i>
            </div>
                <h4 class="text-center">Delete Successfully</h4>
            </div>
        </div>
    </div>
</div>

    <!-- Modal END-->
<script>
    function delete_ach(id){
        console.log(id)
        document.getElementById('deleteach_id').setAttribute('achid',id)
    };
    function conf_delete(){
        var pk  = document.getElementById('deleteach_id').getAttribute("achid");
        $.ajax(
        {
            type:"GET",
            url: "/subscription/delete/"+pk,
            headers: { "X-CSRFToken":getCookie("csrftoken") },

            success: function( data ){
                swal("", "Deleted Successfully", "success").then(function(){
                    location.reload();
                });
                // alert(data.message)
                // window.location.reload();
            },
            statusCode: {
                404: function(response) {
                    console.log('ajax.statusCode: 404');
                    alert('404')
                },
                500: function(response) {
                    alert('500')
                },
                400: function(response) {
                    alert('400')
                },
            }
        })
    };
    function block_unblock(id){
        $.ajax({
            type:"GET",
            url: "/subscription/block_unblock/"+id,
            headers: {"X-CSRFToken":getCookie("csrftoken")},
            success: function(data){
                tags = document.getElementsByTagName("label")
                for(var i=0;i<tags.length;i++){
                    if(tags[i].id==id){
                        if(tags[i].innerHTML==="Block"){
                            tags[i].innerHTML="Unblock"
                        }
                        else{
                            tags[i].innerHTML="Block"
                        }
                    }
                }
                swal("","Updated Successfully","success").then(function(){
                    
                });
            },
            statusCode: {
                404: function(response) {
                    console.log('ajax.statusCode: 404');
                    alert('404')
                },
                500: function(response) {
                    alert('500')
                },
                400: function(response) {
                    alert('400')
                },
            }
        })
    };
    function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for(var i = 0; i <ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }   
        }
        return "";
    };
</script>
<script>        
    function showImportSubmit() {
        document.getElementById("importSubmit").style.display = "inline-block";    
    }
</script>
    
 

    