MyChess/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import activate

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),  # email varification
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    #apps
    path('accounts/',include('accounts.api.urls',namespace='accounts')),
    path('subscription/',include('usubscription.api.urls',namespace='usubscription')),
    path('category/',include('category.api.urls',namespace='category')),
    path('articles/',include('articles.api.urls',namespace='articles')),
    path('game/',include('game.api.urls',namespace='game')),
    path('tournament/',include('tournament.api.urls',namespace='tournament')),
    path('lessons/',include('lessons.api.urls',namespace='lessons')),
    path('achievement/',include('achievement.api.urls',namespace='achievement')),
    path('puzzles/',include('puzzles.api.urls',namespace='puzzles')),
    #admin_panel
    path('admin_panel/',include('_admin_panel.aaccounts.urls',namespace="ap_accounts")),
    path('admin_panel/articles/',include('_admin_panel.aarticles.urls',namespace='ap_articles')),
    path('admin_panel/videos/',include('_admin_panel.avideos.urls',namespace='ap_videos')),
    path('admin_panel/tournament/',include('_admin_panel.atournament.urls',namespace='ap_tournament')),
    path('admin_panel/usermgmt/',include('_admin_panel.ausermgmt.urls',namespace='ap_usermgmt')),
    path('admin_panel/settings/',include('_admin_panel.asettings.urls',namespace='ap_settings')),
    path('admin_panel/notification/',include('_admin_panel.anotification.urls',namespace='ap_notification')),
    path('admin_panel/lessons/',include('_admin_panel.alessons.urls',namespace='ap_lessons')),
    path('admin_panel/gametime/',include('_admin_panel.agametime.urls',namespace='ap_gametime')),
    path('admin_panel/subscription/',include('_admin_panel.asubscription.urls',namespace='ap_subscription')),
    path('admin_panel/leaderboard/',include('_admin_panel.aleaderboard.urls',namespace='ap_leaderboard')),
    path('admin_panel/achievement/',include('_admin_panel.aachievement.urls',namespace='ap_achievement')),
    path('admin_panel/payment/',include('_admin_panel.apayment.urls',namespace='ap_payment')),
    path('admin_panel/puzzles/',include('_admin_panel.apuzzles.urls',namespace='ap_puzzles')),
]
# urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_admin_panel/aleaderboard/urls.py
from django.urls import path
from .views import *
app_name='ap_leaderboard'
urlpatterns = [
    path('list',LeaderBoardListView.as_view(),name='apl_list'),
    path('detail/<int:pk>/<int:rank>',LeaderDetailView.as_view(),name='leader_detail'),
    path('export',LeaderBoardExportView.as_view(),name='leaderboard_export'),
    path('player-point-detail/<int:pk>/<int:tid>',PlayerPointDetailView.as_view(),name='player_point_detail'),
    path('player-point-detail/export',PlayerPointDetailExportView.as_view(),name='player_point_detail_export'),
]

_admin_panel/atournament/urls.py
from django.urls import path
from .views import *
app_name='ap_tournament'
urlpatterns = [
    path('tournament_list',AllTournamentListView.as_view(),name='tournament_list'),
    path('filter_tournament_list',FilterTournamentView.as_view(),name='filter_tournament_list'),
    path('add_tournament',AddTournamentView.as_view(),name='add_tournment'),
    path('view_tournament/<int:pk>',ViewTournament.as_view(),name='view_tournament'),
    path('import_tournament',ImportTournamentView.as_view(),name='import_tournment'),
]

accounts/api/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns=[
    path('countrycode_list',CountryCodeListView.as_view(),name='countrycode_list'),
    path('register',RegisterUserView.as_view(),name='register'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('forgot_password',ForgotPasswordView.as_view(),name='forgot_password'),
    path('otp_send',OTPSendView.as_view(),name='otp_send'),
    path('otp_verify',OTPVerifyAPIView.as_view(),name='otp_verify'),
    path('pass_reset_email',PasswordResetEmailView.as_view(),name='pass_reset_email'),
    path('verify_email',VerifyEmailView.as_view(),name='verify_email'),
    path('create_profile',CreateProfileView.as_view(),name="create_profile"),
    path('update_skill_level',UpdateSkillLevelView.as_view(),name='update_skill_level'),
    path('get_skill_level_list',GetSkillLevelListView.as_view(),name='get_skill_level_list_view'),

    path('block_unblock_user/<int:pk>',BlockUnblockUser.as_view(),name='block_unblock_user'),

    # path('create_notification_group',CreateNotificationGroup.as_view(),name='create_notification_group'),
    path('delete_notification_group/<int:pk>',DeleteNotificationGroup.as_view(),name='delete_notification_group'),
    path('view_notification_group/<int:pk>',ViewNotificationGroup.as_view(),name='view_notification_group'),

    path('many_user_list',ManyUserListView.as_view(),name='many_user_list'),
    path('get_random_online_user',GetRandomOnlineUserView.as_view(),name='get_random_online_user'),


    path('leaderboard/<int:pk>',LeaderBoardView.as_view(),name='get_leaderboard'),
    path('scoreboard',ScoreboardView.as_view(),name='get_scoreboard'),

    
    path('send_notification',SendNotificationView.as_view(),name='send_notification'),

]

_admin_panel/atournament/models.py
from django.db import models

# Create your models here..

_admin_panel/atournament/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, DetailView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import authenticate, login ,logout
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy,reverse
from django.contrib import messages
import datetime
from datetime import datetime
from django.db.models import Count, Max
from django.contrib.sites.shortcuts import get_current_site
import pytz
import openpyxl
import cv2
import re
from django.db.models import Q
from .forms import *
from django.contrib.auth import views as auth_views
from tournament.models import *

class AllTournamentListView(TemplateView):
    def get(self,request,*args,**kwargs):
        tourts = Tournament.objects.all()
        return render(request,'atournament/tournament-all.html',{'tourts':tourts})  

class FilterTournamentView(TemplateView):
    def get(self,request,*args,**kwargs):
        tourts = Tournament.objects.all()
        return render(request,'atournament/tournament-all.html',context={'tourts':tourts})
    def post(self,request,*args,**kwargs):
        startdate_p=request.POST.get('startdate')
        enddate_p=request.POST.get('enddate')
        selection=request.POST.get('selection')

        startdate=startdate_p
        enddate=enddate_p

        if startdate and enddate:
            s=startdate.split('/')
            e=enddate.split('/')
            startdate = datetime(int(s[2]), int(s[0]), int(s[1]), 0, 0, 0, 0, pytz.timezone('Asia/Dubai'))
            enddate = datetime(int(e[2]), int(e[0]), int(e[1]), 23, 59, 59, 999999, pytz.timezone('Asia/Dubai'))
            if selection != 'Select':
                sel = True if selection=='0' else False
                tourts = Tournament.objects.filter(Q(is_active=sel) & Q(Q(start_date__gte=startdate) & Q(end_date__lte=enddate))).order_by('-start_date')
            else:
                tourts = Tournament.objects.filter(Q(start_date__gte=startdate) & Q(end_date__lte=enddate)).order_by('-start_date')
        elif selection != 'Select':
            sel = True if selection=='0' else False
            tourts = Tournament.objects.filter(is_active=sel).order_by('-start_date')
        else:
            tourts = Tournament.objects.all().order_by('-start_date')

        return render(request,'atournament/tournament-all.html',context={'tourts':tourts, 'selection':selection, 'startdate':startdate_p, 'enddate':enddate_p})

class AddTournamentView(TemplateView):
    def get(self,request,*args,**kwargs):
        return render(request,'atournament/add-tournament.html',)  
    def post(self,request,*args,**kwargs):
        form = CreateTournamentForm(data=request.POST or None,)
        message=''
        context=''
        tname = request.POST['tname']
        tstart_date = request.POST['tstart_date']
        tend_date = request.POST['tend_date']
        # tduration = request.POST['tduration'] 
        tlimit = request.POST['tlimit']
        tcond = request.POST.getlist('tcond')
        thh = request.POST['thh']
        tmm = request.POST['tmm']
        trounds = request.POST['trounds']
        trating = request.POST['trating']

        print(tcond)
        
        if form.is_valid():
            tstart_date=tstart_date.split('/')
            tend_date=tend_date.split('/')
            tstart_date = datetime.date(int(tstart_date[2]),int(tstart_date[0]),int(tstart_date[1]))
            tend_date = datetime.date(int(tend_date[2]),int(tend_date[0]),int(tend_date[1]))

            thh = int(thh)
            tmm = int(tmm)
            tstart_time = datetime.time(thh, tmm, 00)

            t = Tournament(
                name = tname,
                game_time_limit = tlimit,
                start_date = tstart_date,
                end_date = tend_date,
                duration = 10,
                start_time = tstart_time,
                rounds = trounds,
                rating = trating,
                # duration = tduration,
            )
            t.save()
            if '1' in tcond:
                print('hi')
                t.is_only_sub_members = True
            if '2' in tcond:
                print('hello')
                t.is_entry_before_tournament = True
            if '3' in tcond:
                t.is_entry_after_half_time = True
            t.save()

            send_notification_to_all()

            message="Tournament added successfully"
            messages.add_message(request, messages.INFO, message)
            return render(request,'atournament/add-tournament.html')

        context = {
            'tname':tname,
            'tstart_date':tstart_date,
            'tend_date':tend_date,
            # 'tduration':tduration,
            'tlimit':tlimit,
            'tcond':tcond,
            'thh': thh,
            'tmm': tmm,
            'trounds': trounds,
            'trating': trating
        }
        messages.add_message(request, messages.INFO, message)
        return render(request,'atournament/add-tournament.html',{'form':form,'context':context})

class ViewTournament(TemplateView):
    def get(self,request,*args,**kwargs):
        id = self.kwargs['pk']
        tourt = Tournament.objects.filter(id=id).first()

        total_game_played=""
        most_games_played_by=""
        most_games_won_by=""
        most_games_lost_by=""
        best_winning_streak=""
        leader_board=""

        total_game_played = TournamentGameManager.objects.filter(tournament=tourt).count()
        if total_game_played!=0:
            most_games_played_by = TournamentPlayerManager.objects.filter(tournament=tourt).annotate(Max('total_games_played')).order_by('-total_games_played__max').first().player.name
            most_games_won_by = TournamentPlayerManager.objects.filter(tournament=tourt).annotate(Max('total_games_won')).order_by('-total_games_won__max').first().player.name
            most_games_lost_by = TournamentPlayerManager.objects.filter(tournament=tourt).annotate(Max('total_games_lost')).order_by('-total_games_lost__max').first().player.name
            best_winning_streak = TournamentGameManager.objects.filter(tournament=tourt).values('winning_streak').annotate(Count('id')).order_by('-id__count').first()['winning_streak']

            leader_board = TournamentPlayerManager.objects.filter(tournament=tourt).order_by('-points')[0:10]

        return render(request,'atournament/view-tournament.html',context={
                                                                    'tourt':tourt,
                                                                    'total_game_played':total_game_played,
                                                                    'most_games_played_by':most_games_played_by,
                                                                    'most_games_won_by':most_games_won_by,
                                                                    'most_games_lost_by':most_games_lost_by,
                                                                    'best_winning_streak':best_winning_streak,
                                                                    'leader_board':leader_board,
                                                                })  

class ImportTournamentView(TemplateView):
    def get(self,request,*args,**kwargs):
        tourts = Tournament.objects.all()        
        return render(request,'atournament/tournament-all.html',{'tourts':tourts}) 
    def post(self,request,*args,**kwargs):    
        message=''    
        excel_file = request.FILES["excel_file"]
        wb = openpyxl.load_workbook(excel_file)
        worksheet = wb["Sheet1"]
        print(worksheet)
        excel_data = list()
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)

        status = validate_excel(excel_data)
        print(status)
        if status!="1":
            messages.add_message(request, messages.INFO, status)
            return HttpResponseRedirect('/admin_panel/tournament/tournament_list')
        
        counter=0
        for row_data in excel_data:
            counter+=1
            if counter!=1:
                thh = int(row_data[3].split(':')[0])
                tmm = int(row_data[3].split(':')[1])
                tstart_time = datetime.time(thh, tmm, 00)
                t = Tournament(
                    name = row_data[0],
                    start_date = row_data[1].split(' ')[0],
                    end_date = row_data[2].split(' ')[0],
                    duration = 10,
                    start_time = tstart_time,
                    rounds = row_data[4],
                    game_time_limit = row_data[5],
                    rating = row_data[6],
                )
                t.save()
                t.is_only_sub_members = True if row_data[7] == '1' else False
                t.is_entry_before_tournament = True if row_data[8] == '1' else False
                t.is_entry_after_half_time = True if row_data[9] == '1' else False
                t.save()

        message='Data saved successfully'
        messages.add_message(request, messages.INFO, message)
        return HttpResponseRedirect('/admin_panel/tournament/tournament_list')

def validate_excel(excel_data):
    counter=0
    if len(excel_data[0])<8:
        return 'Please use proper excel file format'
    if len(excel_data)==1:
        return 'There is no data available in the file'
    for row_data in excel_data:
        print(row_data)
        print(row_data[0])
        counter += 1
        tName=row_data[0]
        tStartDate=row_data[1]
        tEndDate=row_data[2]
        # tDuration=row_data[3]
        tStartTime=row_data[3]
        tRounds=row_data[4]
        tTimeLimit=row_data[5]
        tRating=row_data[6]
        tC1=row_data[7]
        tC2=row_data[8]

_admin_panel/atournament/templates/atournament/view-tournament.html
{% load staticfiles %}
{% include 'base/header-link.html' %}
{% include 'base/header.html' %}
<div class="layout-main">
    {% include 'base/sidebar.html' %}

    <div class="userPage ExplorerListPage">
        <div class="layout-content">
            <div class="layout-content-body">
                    <div class="row margin-bottom-15">
                        <div class="col-md-6">
                            <div class="title-bar">
                                <h1 class="title-bar-title">
                                    <span class="d-ib">Tournament Management-View</span>
                                </h1>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="category-select">
                                <a class="btn btn-danger" href="{% url 'ap_tournament:tournament_list' %}">Back</a>
                            </div>
                        </div>
                    </div>
                <div class="row gutter-xs">
                    <div class="col-xs-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="card-actions">
                                    <button type="button" class="card-action card-toggler" title="Collapse"></button>
                                    <button type="button" class="card-action card-reload" title="Reload"></button>

                                </div>    
                            </div>
                            <div class="card-body">
                                <div class="form-horizontal">
                                    <div class="row">
                                        <div class="col-md-6">                        
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="fname">Id</label>
                                                <div class="col-sm-6">
                                                    <input type="fname" class="form-control" id="fname" value="{{tourt.id}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="fname">Name</label>
                                                <div class="col-sm-6">
                                                    <input type="fname" class="form-control" id="fname" value="{{tourt.name}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="fname">The Limit Per Game(mins)</label>
                                                <div class="col-sm-6">
                                                    <input type="fname" class="form-control" id="fname" value="{{tourt.game_time_limit}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-md-6">                        
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="fname">Start Date</label>
                                                <div class="col-sm-6">
                                                    <input type="phone" class="form-control" id="fname" value="{{tourt.start_date}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="email">End Date</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="email" value="{{tourt.end_date}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4">Duration(days)</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="duration" value="{{tourt.duration}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                        </div>
                                      </div>
                                      <hr>
                                      <div class="row">
                                            <div class="col-md-6"> 
                                            <div class="col-md-12"> 
                                                <div class="form-group">
                                                    <h4>Tournament Status</h4>
                                                </div>
                                            </div>                   
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="fname">Total Game Played</label>
                                                <div class="col-sm-6">
                                                    <input type="phone" class="form-control" id="fname" value="{{total_game_played}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4" for="email">Most Games Played By</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="email" value="{{most_games_played_by}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4">Most Games Won By</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="duration" value="{{most_games_won_by}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4">Most Games Lost By</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="duration" value="{{most_games_lost_by}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label col-sm-4">Best Winning Streak</label>
                                                <div class="col-sm-6">
                                                    <input type="text" class="form-control" id="duration" value="{{best_winning_streak}}" placeholder="" readonly>
                                                </div>
                                            </div>
                                            </div>
                                            <div class="col-md-6"> 
                                                <div class="col-md-12"> 
                                                    <div class="form-group">
                                                        <h4>Leader Board Ranking</h4>
                                                    </div>
                                                </div>  
                                                <!-- <div class="col-md-12" style="background-color: aquamarine;">  -->
                                                    <div class="sroll-y">                 
                                                        <div class="form-group">
                                                            <label class="control-label col-sm-2" for="fname" style="display: block;">Rank</label>
                                                            <div class="col-sm-4">
                                                                <label class="control-label col-sm-4" for="fname">Name</label>
                                                            </div>
                                                            <div class="col-sm-3">
                                                                <label class="control-label col-sm-3" for="fname">Point</label>
                                                            </div>
                                                            <div class="col-sm-3">
                                                                <label class="control-label col-sm-3" for="fname">Detail</label>
                                                            </div>
                                                            <br>
                                                            <hr>
                                                            {% for x in leader_board %}
                                                                <label class="control-label col-sm-2" for="fname">Rank {{forloop.counter}}</label>
                                                                <div class="col-sm-4">
                                                                    <input type="phone" class="form-control" id="fname" value="{{x.player.name}}" placeholder="" readonly>
                                                                </div>
                                                                <div class="col-sm-3">
                                                                    <input type="phone" class="form-control" id="fname" value="{{x.points}}" placeholder="" readonly>
                                                                </div>
                                                                <div class="col-sm-3">
                                                                    <a class="btn btn-primary btn-sm btn-labeled" href="{% url 'ap_leaderboard:player_point_detail' x.player.id tourt.id %}">
                                                                        <span class="btn-label">
                                                                        <span class="icon fa fa-eye icon-fw icon-lg f-16"></span>
                                                                        </span>
                                                                        Match Wise Detail
                                                                    </a>
                                                                </div>
                                                            {% endfor %}
                                                        </div>
                                                    </div>
                                                <!-- </div> -->
                                            </div>    
                                      </div> 
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% include 'base/footer-link.html' %}
    {% include 'base/footer.html' %}
  
    