MyChess/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import activate

urlpatterns = [
    path('admin/', admin.site.urls),
    url('^', include('django.contrib.auth.urls')),  # email varification
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',activate, name='activate'),
    #apps
    path('accounts/',include('accounts.api.urls',namespace='accounts')),
    path('subscription/',include('usubscription.api.urls',namespace='usubscription')),
    path('category/',include('category.api.urls',namespace='category')),
    path('articles/',include('articles.api.urls',namespace='articles')),
    path('game/',include('game.api.urls',namespace='game')),
    path('tournament/',include('tournament.api.urls',namespace='tournament')),
    path('lessons/',include('lessons.api.urls',namespace='lessons')),
    path('achievement/',include('achievement.api.urls',namespace='achievement')),
    path('puzzles/',include('puzzles.api.urls',namespace='puzzles')),
    #admin_panel
    path('admin_panel/',include('_admin_panel.aaccounts.urls',namespace="ap_accounts")),
    path('admin_panel/articles/',include('_admin_panel.aarticles.urls',namespace='ap_articles')),
    path('admin_panel/videos/',include('_admin_panel.avideos.urls',namespace='ap_videos')),
    path('admin_panel/tournament/',include('_admin_panel.atournament.urls',namespace='ap_tournament')),
    path('admin_panel/usermgmt/',include('_admin_panel.ausermgmt.urls',namespace='ap_usermgmt')),
    path('admin_panel/settings/',include('_admin_panel.asettings.urls',namespace='ap_settings')),
    path('admin_panel/notification/',include('_admin_panel.anotification.urls',namespace='ap_notification')),
    path('admin_panel/lessons/',include('_admin_panel.alessons.urls',namespace='ap_lessons')),
    path('admin_panel/gametime/',include('_admin_panel.agametime.urls',namespace='ap_gametime')),
    path('admin_panel/subscription/',include('_admin_panel.asubscription.urls',namespace='ap_subscription')),
    path('admin_panel/leaderboard/',include('_admin_panel.aleaderboard.urls',namespace='ap_leaderboard')),
    path('admin_panel/achievement/',include('_admin_panel.aachievement.urls',namespace='ap_achievement')),
    path('admin_panel/payment/',include('_admin_panel.apayment.urls',namespace='ap_payment')),
    path('admin_panel/puzzles/',include('_admin_panel.apuzzles.urls',namespace='ap_puzzles')),
]
# urlpatterns += [url(r'^silk/', include('silk.urls', namespace='silk'))]
if settings.DEBUG:
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_admin_panel/apuzzles/urls.py
from django.urls import path
from .views import *

app_name = 'ap_puzzles'

urlpatterns = [
    path('categories',PuzzleCategoriesListView.as_view(),name='ap_p_categories'),
    path('categories/add',PuzzleCategoriesAddView.as_view(),name='ap_p_categories_add'),
    path('categories/view/<int:pk>',PuzzleCategoriesViewView.as_view(),name='ap_p_categories_view'),
    path('categories/edit/<int:pk>',PuzzleCategoriesEditView.as_view(),name='ap_p_categories_edit'),
    path('categories/import',PuzzleCategoriesImportView.as_view(),name='ap_p_categories_import'),
    path('list',PuzzlesListView.as_view(),name='ap_p_puzzles'),
    path('list/add',PuzzlesAddView.as_view(),name='ap_p_puzzles_add'),
    path('list/view/<int:pk>',PuzzlesViewView.as_view(),name='ap_p_puzzles_view'),
    path('list/edit/<int:pk>',PuzzlesEditView.as_view(),name='ap_p_puzzles_edit'),
    path('list/import',PuzzlesImportView.as_view(),name='ap_p_puzzles_import'),
]

accounts/api/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns=[
    path('countrycode_list',CountryCodeListView.as_view(),name='countrycode_list'),
    path('register',RegisterUserView.as_view(),name='register'),
    path('login',LoginView.as_view(),name='login'),
    path('logout',LogoutView.as_view(),name='logout'),
    path('forgot_password',ForgotPasswordView.as_view(),name='forgot_password'),
    path('otp_send',OTPSendView.as_view(),name='otp_send'),
    path('otp_verify',OTPVerifyAPIView.as_view(),name='otp_verify'),
    path('pass_reset_email',PasswordResetEmailView.as_view(),name='pass_reset_email'),
    path('verify_email',VerifyEmailView.as_view(),name='verify_email'),
    path('create_profile',CreateProfileView.as_view(),name="create_profile"),
    path('update_skill_level',UpdateSkillLevelView.as_view(),name='update_skill_level'),
    path('get_skill_level_list',GetSkillLevelListView.as_view(),name='get_skill_level_list_view'),

    path('block_unblock_user/<int:pk>',BlockUnblockUser.as_view(),name='block_unblock_user'),

    # path('create_notification_group',CreateNotificationGroup.as_view(),name='create_notification_group'),
    path('delete_notification_group/<int:pk>',DeleteNotificationGroup.as_view(),name='delete_notification_group'),
    path('view_notification_group/<int:pk>',ViewNotificationGroup.as_view(),name='view_notification_group'),

    path('many_user_list',ManyUserListView.as_view(),name='many_user_list'),
    path('get_random_online_user',GetRandomOnlineUserView.as_view(),name='get_random_online_user'),


    path('leaderboard/<int:pk>',LeaderBoardView.as_view(),name='get_leaderboard'),
    path('scoreboard',ScoreboardView.as_view(),name='get_scoreboard'),

    
    path('send_notification',SendNotificationView.as_view(),name='send_notification'),

]

puzzles/api/urls.py
from django.urls import path
from .views import *
app_name='puzzles'
urlpatterns = [
    path('blockunblock/<int:pk>',BlockUnblockPuzzleView.as_view(),name='p_block'),
    path('delete/<int:pk>',DeletePuzzleView.as_view(),name='p_delete'),
    path('blockunblocklc/<int:pk>',BlockUnblockPuzzleCatView.as_view(),name='pc_block'),
    path('deletelc/<int:pk>',DeletePuzzleCatView.as_view(),name='pc_delete'),

    path('puzzle-cat-list',PuzzleCatListView.as_view(),name='p_cat_list'),
    path('puzzle-cat-detail/<int:pk>',PuzzleCatDetailView.as_view(),name='p_cat_detail'),
    path('puzzle-list',PuzzleListView.as_view(),name='p_list'),
    path('puzzle-detail/<int:pk>',PuzzleDetailView.as_view(),name='p_detail'),

    path('puzzle-solved',PuzzleSolvedView.as_view(),name='p_solved')
]

_admin_panel/apuzzles/models.py
from django.db import models

# Create your models here.

_admin_panel/apuzzles/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.contrib import messages
import openpyxl
import cv2
from puzzles.models import *
from .forms import *


# Create your views here.
class PuzzleCategoriesListView(TemplateView):
    def get(self,request,*args, **kwargs):
        lcs = PuzzleCategory.objects.all()
        for l in lcs:
            count = Puzzle.objects.filter(category=l).count()
            l.count = count
        return render(request,'apuzzles/puzzle-categories.html',{'lcs':lcs})

class PuzzleCategoriesAddView(TemplateView):
    def get(self,request,*args, **kwargs):
        less = Puzzle.objects.filter(is_blocked=False)
        return render(request,'apuzzles/add-puzzle-category.html',{'less':less})
    def post(Self,request,*args,**kwargs):
        less = Puzzle.objects.filter(is_blocked=False)

        context={}
        cr_name = request.POST['cr_name']
        cr_icon = request.FILES.get('cr_icon')
        cr_list = request.POST['cr_list']
        
        context['cr_name']=cr_name
        context['cr_icon']=cr_icon
        form = PuzzleCategoriesAddForm(request.POST or None)
        lcobj=''
        lobjlist=[]
        cr_list = cr_list.split(',')
        for c in cr_list:
            if c:
                lobj = Puzzle.objects.filter(id=c).first()
                lobjlist.append(lobj)
        context['cr_list'] = lobjlist

        if form.is_valid():
            x=0
            if cr_icon:
                if cr_icon.size>5242880:
                    x=1
                    message="Category icon size is not valid"
                if cr_icon.name.split('.')[-1].lower() not in ('jpg','jpeg','png'):
                    x=1
                    message="Category icon extension is not valid"

            if x==1:
                messages.add_message(request, messages.INFO, message)
                return render(request,'apuzzles/add-puzzle-category.html',{'form':form,'less':less,'context':context})


            if cr_icon:
                lcobj = PuzzleCategory(
                    name = cr_name,
                    icon = cr_icon,
                )
                lcobj.save()
                lcobj.iconurl=lcobj.icon.url
                lcobj.save()
            else:
                lcobj = PuzzleCategory(
                    name = cr_name,
                )
                lcobj.save()
            if lobjlist:
                for lobj in lobjlist:
                    if lobj:
                        lobj.category = lcobj
                        lobj.save()
            message = 'Puzzle category created successfully'
            messages.add_message(request, messages.INFO, message)
            return render(request,'apuzzles/add-puzzle-category.html',{'less':less,})

        return render(request,'apuzzles/add-puzzle-category.html',{'form':form,'less':less,'context':context})

class PuzzleCategoriesViewView(TemplateView):
    def get(self,request,*args, **kwargs):
        id = self.kwargs['pk']
        lc = PuzzleCategory.objects.filter(id=id).first()
        lss = Puzzle.objects.filter(category=lc)
        return render(request,'apuzzles/puzzle-category-view.html',{'lc':lc,'lss':lss})

class PuzzleCategoriesEditView(TemplateView):
    def get(self,request,*args, **kwargs):
        id = self.kwargs['pk']
        lc = PuzzleCategory.objects.filter(id=id).first()
        lss = Puzzle.objects.filter(category=lc)

        context={}
        context['cr_id'] = lc.id
        context['cr_name'] = lc.name
        context['cr_icon'] = lc.iconurl
        context['cr_list'] = lss

        less = Puzzle.objects.filter(is_blocked=False)
        return render(request,'apuzzles/puzzle-category-edit.html',{'context':context,'less':less})
    
    def post(self,request, *args, **kwargs):
        id = self.kwargs['pk']
        lc = PuzzleCategory.objects.filter(id=id).first()
        less = Puzzle.objects.filter(is_blocked=False)

        context={}
        
        cr_id = lc.id
        cr_name = request.POST['cr_name']
        cr_icon = request.FILES.get('cr_icon')
        cr_list = request.POST['cr_list']
        
        context['cr_id']=cr_id
        context['cr_name']=cr_name
        context['cr_icon']=cr_icon
        form = PuzzleCategoriesEditForm(request.POST or None, cr_id)
        
        lobjlist=[]
        cr_list = cr_list.split(',')
        for c in cr_list:
            if c:
                lobj = Puzzle.objects.filter(id=c).first()
                lobjlist.append(lobj)
        context['cr_list'] = lobjlist

        if form.is_valid():
            x=0
            if cr_icon:
                if cr_icon.size>5242880:
                    x=1
                    message="Category icon size is not valid"
                if cr_icon.name.split('.')[-1].lower() not in ('jpg','jpeg','png'):
                    x=1
                    message="Category icon extension is not valid"

            if x==1:
                messages.add_message(request, messages.INFO, message)
                return render(request,'apuzzles/puzzle-category-edit.html',{'form':form,'less':less,'context':context})


            if cr_icon:
                lc.name = cr_name
                lc.icon = cr_icon
                lc.save()
                lc.iconurl=lc.icon.url
                lc.save()
            else:
                lc.name = cr_name
                lc.save()
            if lobjlist:
                for lobj in lobjlist:
                    if lobj:
                        lobj.category = lc
                        lobj.save()
            message = 'Puzzle category updated successfully'
            messages.add_message(request, messages.INFO, message)
            return HttpResponseRedirect('/admin_panel/puzzles/categories/view/'+str(cr_id))

        return render(request,'apuzzles/puzzle-category-edit.html',{'form':form,'less':less,'context':context})

class PuzzleCategoriesImportView(TemplateView):
    def post(self,request,*args,**kwargs):
        message=''
        excel_file = request.FILES["excel_file"]

        # you may put validations here to check extension or file size 

        wb = openpyxl.load_workbook(excel_file)

        # getting a particular sheet by name out of many sheets
        worksheet = wb["Sheet1"]
        print(worksheet)
        
        excel_data = list()
        # iterating over the rows and
        # getting value from each cell in row
        for row in worksheet.iter_rows():
            row_data = list()
            for cell in row:
                row_data.append(str(cell.value))
            excel_data.append(row_data)

        status = validate_less_cat_excel(excel_data)
        if status!="1":
            messages.add_message(request, messages.INFO, status)
            return HttpResponseRedirect('/admin_panel/puzzles/categories')     
        
        # try:
        counter=0
        for row_data in excel_data:
            counter+=1            
            if counter!=1:
                lesscat = PuzzleCategory(
                    name=row_data[0],
                    iconurl=row_data[1],
                )
                lesscat.save()
                lessids = row_data[2]
                if lessids:
                    if ',' in lessids:
                        lessidslist=lessids.split(',')
                        for v in lessidslist:
                            vobj=Puzzle.objects.filter(id=v).first()
                            vobj.category=lesscat
                            vobj.save()
                    else:
                        if not lessids or lessids == 'None' or lessids=="":
                            pass
                        else:
                            vobj=Puzzle.objects.filter(id=lessids).first()
                            vobj.category=lesscat
                            vobj.save()

                message='Data saved successfully'

        messages.add_message(request, messages.INFO, message)
        return HttpResponseRedirect('/admin_panel/puzzles/categories')

def validate_less_cat_excel(excel_data):
    counter=0
    less_id_list=[]
    if len(excel_data[0])<3:
        return 'Please use proper excel file format'
    for row_data in excel_data:
        counter += 1

        catName=row_data[0]
        catIcon=row_data[1]
        lessIds=row_data[2]
        
        print(counter)
        if counter==1:
            print(catName)
            print(catIcon)
            print(lessIds)
            if (catName!='Category Name' or catIcon!='Category Icon Link' 
                or lessIds!='Puzzle Ids'):
                return 'Please use proper excel file format'
        else:
            if not catName or catName=="" or catName=='None':
                return 'Please provide category name at row '+str(counter)
            if not catIcon or catIcon=="" or catIcon=='None':
                return 'Please provide category icon '+str(counter)

            if ',' in lessIds:
                lessIdsList = lessIds.split(',')
                for v in lessIdsList:
                    vid = Puzzle.objects.filter(id=int(v)).first()
                    less_id_list.append(v)
                    if not vid:
                        return "Puzzle id "+v+" is not correct at row "+str(counter)
            else:
                if not lessIds or lessIds == 'None' or lessIds=="":
                    pass
                else:
                    vid = Puzzle.objects.filter(id=int(lessIds)).first()
                    less_id_list.append(lessIds)
                    if not vid:
                        return "Puzzle id "+lessIds+" is not correct at row "+str(counter)

            if len(catName)>90:
                return "Category name length is exceeding at row "+str(counter)
            if len(catIcon)>8500:
                return "Category Icon length is exceeding at row "+str(counter)
            if 'http' not in catIcon:

puzzles/views.py
from django.shortcuts import render

# Create your views here.

_admin_panel/apuzzles/templates/apuzzles/puzzle-categories.html
{% load staticfiles %}
{% include 'base/header-link.html' %}
{% include 'base/header.html' %}
<div class="layout-main">
{% include 'base/sidebar.html' %}

    <div class="lessonPage ExplorerListPage">
        <div class="layout-content">
            <div class="layout-content-body">
                    <div class="row margin-bottom-15">
                        <div class="col-md-12">
                            <div class="title-bar">
                                <h1 class="title-bar-title">
                                    <span class="d-ib">Puzzles Management - Categories</span>
                                </h1>
                            </div>
                        </div>
                    </div>
                    <div class="row margin-bottom-15">
                        <form action="{% url 'ap_puzzles:ap_p_categories_import' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="col-sm-12">
                                <div class="add_member category-select">
                                    <p style="color:blue;">After importing the file please click the submit button</p>
                                    <input type="file" accept=".xls,.xlsx" name="excel_file" id="import" onchange="showImportSubmit(); return false;" class="hidden">
                                    <a class="btn btn-danger btn-sm btn-labeled" href="{% url 'ap_puzzles:ap_p_categories_add' %}">
                                        <span class="btn-label">
                                        <i class="fa fa-plus" aria-hidden="true"></i>
                                        </span>
                                        ADD
                                    </a>
                                    <label class="btn btn-danger btn-sm btn-labeled" for="import">
                                        <span class="btn-label">
                                        <i class="fa fa-file-excel-o" aria-hidden="true"></i>
                                        </span>
                                        Import
                                    </label>
                                    <button id="importSubmit" class="btn btn-danger btn-sm btn-labeled" type="submit" style="display: none;">
                                        <span class="btn-label">
                                        <i class="fa fa-paper-plane" aria-hidden="true"></i>
                                        </span>
                                        Submit
                                    </button>
                                    {% if messages %}
                                        {% for message in messages %}
                                            <p style="color:green;">{{message}}</p>
                                        {% endfor %}
                                    {% endif %}
                                </div> 
                            </div> 
                        </form> 
                    </div> 
                <div class="row gutter-xs">
                    <div class="col-xs-12">
                        <div class="card">
                            <div class="card-body">
                                <div class="table-responsive">
                                <table id="demo-datatables-5" class="table table-striped table-bordered table-nowrap dataTable" cellspacing="0" width="100%">
                                    <thead>
                                        <tr>
                                            <th width="6%">S.No ID</th>
                                            <th>Category ID</th>
                                            <th>Category Name</th>
                                            <th>Number of Puzzles</th>
                                            <th width="20%">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for l in lcs %}
                                            <tr>
                                                <td>{{forloop.counter}}</td>
                                                <td>{{l.id}}</td>
                                                <td><span class="p-txt"> {{l.name}}</span></td>
                                                <td>{{l.count}}</td>
                                                <td>
                                                    <button id="{{l.id}}" class="btn btn-danger btn-sm btn-labeled" type="button" data-toggle="modal" data-target="#deleteUser" onclick="deletelesson(this.id)">
                                                        <span class="btn-label">
                                                        <span class="icon fa fa-trash icon-fw icon-lg f-16"></span>
                                                        </span>
                                                        Delete
                                                    </button>
                                                    <a class="btn btn-primary btn-sm btn-labeled" href="{% url 'ap_puzzles:ap_p_categories_view' l.id %}">
                                                        <span class="btn-label">
                                                        <span class="icon fa fa-eye icon-fw icon-lg f-16"></span>
                                                        </span>
                                                        View
                                                    </a>
                                                    <button class="btn btn-default btn-sm btn-labeled" type="button">
                                                        {% if l.is_blocked %}
                                                            <span class="btn-label">
                                                                <label class="mr-2 switch product-switch">
                                                                    <input id="{{l.id}}" type="checkbox" onchange="blockunblocklesson(this.id)">
                                                                    <span class="slider round product-slide"></span>
                                                                </label>
                                                            </span>
                                                            <label id="{{l.id}}" for="">Unblock</label>
                                                        {% else %}
                                                            <span class="btn-label">
                                                                <label class="mr-2 switch product-switch">
                                                                    <input id="{{l.id}}" type="checkbox" checked="" onchange="blockunblocklesson(this.id)">
                                                                    <span class="slider round product-slide"></span>
                                                                </label>
                                                            </span>
                                                            <label id="{{l.id}}" for="">Block</label>
                                                        {% endif %}
                                                    </button>    
                                                </td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% include 'base/footer.html' %}
    {% include 'base/footer-link.html' %}
    
    <div id="deleteUser" tabindex="-1" role="dialog" class="modal fade">
     <div class="modal-dialog modal-sm">
        <div class="modal-content">
          <div class="modal-body">
            <div class="text-center">
              <h4>Are you sure you want to Delete this Puzzle category?</h4>
              <div class="m-t-lg">
                <button id="lessiondeleteconfirm" class="btn btn-red" data-dismiss="modal" type="button" data-toggle="modal" lessionid="" onclick="deleteConfirm()">Continue</button>
                <button class="btn btn-default" data-dismiss="modal" type="button">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
   
    <!-- Modal -->
<div class="modal fade" id="exampleModalLong">
    <div class="modal-dialog modal-sm" data-dismiss="modal">
        <div class="modal-content">
            <div class="modal-body">
            <div class="successful-icon text-center">
            <i class="fa fa-check-square-o" aria-hidden="true" style="font-size: 22px;color: #17b517;"></i>
            </div>
                <h4 class="text-center">Delete Successfully</h4>
            </div>
        </div>
    </div>
</div>

    <!-- Modal END-->
<script>
    function deletelesson(clicked_id){
        document.getElementById('lessiondeleteconfirm').setAttribute('lessionid',clicked_id);
    }
    function deleteConfirm(){
        var pk = document.getElementById('lessiondeleteconfirm').getAttribute('lessionid');
        $.ajax({

            type:"POST",
            url: "/puzzles/deletelc/"+pk,
            headers: { "X-CSRFToken":getCookie("csrftoken") },

            success: function( data ){
                swal("", "Deleted Successfully", "success").then(function(){
                    location.reload();
                });
                    // alert(data.message)
                    // window.location.reload();
            },

            statusCode: {
                404: function(response) {
                    console.log('ajax.statusCode: 404');
                    alert('404')
                },
                500: function(response) {
                    alert('500')
                },
                400: function(response) {
                    alert('400')
                },
            }
        })
    }
    function blockunblocklesson(clicked_id){
        $.ajax({
            type:"POST",
            url: "/puzzles/blockunblocklc/"+clicked_id,
            headers: {"X-CSRFToken":getCookie("csrftoken")},
            success: function(data){
                tags = document.getElementsByTagName("label")
                for(var i=0;i<tags.length;i++){
                    if(tags[i].id==clicked_id){
                        if(tags[i].innerHTML==="Block"){
                            tags[i].innerHTML="Unblock"
                        }
                        else{
                            tags[i].innerHTML="Block"
                        }
                    }
                }
                swal("","Updated Successfully","success").then(function(){
                    
                });
            },
            statusCode: {
                404: function(response) {
                    console.log('ajax.statusCode: 404');
                    alert('404')
                },
                500: function(response) {
                    alert('500')
                },
                400: function(response) {
                    alert('400')
                },
            }
        })
    };
    function getCookie(cname) {
        var name = cname + "=";
        var decodedCookie = decodeURIComponent(document.cookie);
        var ca = decodedCookie.split(';');
        for(var i = 0; i <ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
            c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
            }
        }
        return "";
    }
</script>
<script>        
    function showImportSubmit() {
        document.getElementById("importSubmit").style.display = "inline-block";    
    }
</script>

    